move vaults to inactive
harvest-finance/harvest-api pull request #201
Opened 2022-05-02 18:02 UTC by Crypto-One-dev

2022-05-03 15:07 UTC, hubert895 requested changes
Incorrect categories

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_POLYGON,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_POLYGON,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_BSC,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_BSC,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_BSC,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_BSC,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_BSC,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_BSC,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_POLYGON,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_POLYGON,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_POLYGON,
```

2022-05-03 15:07 UTC, hubert895 commented on data/mainnet/tokens.js
> +    category: VAULT_CATEGORIES_IDS.INACTIVE,
```suggestion
    category: VAULT_CATEGORIES_IDS.INACTIVE_POLYGON,
```

2022-05-04 12:59 UTC, CryptJS13 commented
Please also change the hardwork settings in the `addresses.json` file

2022-05-04 23:09 UTC, hubert895 approved these changes

2022-05-05 06:41 UTC, Crypto-One-dev commented
> Please also change the hardwork settings in the `addresses.json` file

Fixed for dohardwork settings. Please check

2022-05-09 08:16 UTC, merged