ApeStake: ApeCoin Pool Apy
harvest-finance/harvest-api pull request #241
Opened 2023-01-16 03:01 UTC by tommy4241

2023-01-16 14:47 UTC, CryptJS13 requested changes
Hey @tommy4241, few comments that need to be fixed. Thanks!

2023-01-16 14:47 UTC, CryptJS13 commented on data/mainnet/tokens.js
> +    displayName: 'ApeStake',
Lets rename to 'APE'

2023-01-16 14:47 UTC, CryptJS13 commented on data/mainnet/tokens.js
> +    subLabel: 'ApeStake APECOIN Pool',
This line can be removed

2023-01-16 16:53 UTC, tommy4241 commented on src/vaults/apys/implementations/ape-stake.js
> +    currentTimeStamp + ONE_YEAR,
I see. Good Point!

2023-01-17 12:45 UTC, CryptJS13 approved these changes
Thanks! Looks good!

2023-01-18 20:05 UTC, merged